### ISSUE TITLE
Directly download from f-droid and differences from other packages

### ISSUE THREAD

**Issue by jarry9** [adolfintel/chromiumUpdater#10]
Hi,

First thank you for this development...

1- Why you don't add the chromium-apk directly to f-droid. So we can directly download the app from f-droid like other apps.

2- There is another android app for same purpose: https://github.com/andDevW/getChromium You know what is the difference with your app?

Thanks in advance...

**Comment by adolfintel** [comment]
We can't upload the Chromium APK directly to f-droid for several resons: license, build system, frequency of updates, and more.
The difference between my application and getChromium is the installation method. We download from the same source, but mine can install Chromium silently, and checks updates periodically, while getChromium (last I checked) didn't even have a progress bar, and installation was manual.

**Comment by jarry9** [comment]
Thanks for information...
