### ISSUE TITLE
fails on replicant 6

### ISSUE THREAD

**Issue by ian-kelling** [adolfintel/chromiumUpdater#12]
Installed, clicked update now. I turned on show internal errors. It's truncated and I don't know how to see the full error, but it says

java.io.FileNotFoundException: /sorage/emulated/..

I'm using 1.7 from fdroid.

**Comment by adolfintel** [comment]
Looks like it can't write to your internal sdcard

**Comment by ian-kelling** [comment]
Anyways, chromium just crashes on replicant due to proprietary opengl stuff that replicant took out and chromium requires.
