### ISSUE TITLE
Offer "stable" version

### ISSUE THREAD

**Issue by AeliusSaionji** [adolfintel/chromiumUpdater#16]
While there is no official stable release for chromium, in other repositories the "stable" version of chromium is considered to be the version that matches the current chrome release. This is fairly common across linux package managers. I'm hoping to get a similar experience on f-droid!

**Comment by adolfintel** [comment]
If there's some way to get the build number of that version, I will do it

**Comment by AeliusSaionji** [comment]
Does this help? https://chromium.woolyss.com/#api

**Comment by adolfintel** [comment]
Nope, it points to the latest build:
https://chromium.woolyss.com/api/?os=android&out=xml

**Comment by adolfintel** [comment]
I think at the moment the only way I could do that would be to host it on my site, but that kinda defeats the whole point of the updater, to fetch updates directly from google

**Comment by pgera** [comment]
Is it possible to use the same api that yalp store uses to get the chrome version string ?https://github.com/yeriomin/YalpStore

**Comment by adolfintel** [comment]
You need the build number, not the version string, and even then, sometimes the build number of Chrome can't be found under the Chromium builds.
Unless there's some sort of API to get a "stable" build number, there is no way I can offer that.

**Comment by pgera** [comment]
On https://www.chromium.org/getting-involved/download-chromium, there is some information about getting specific old versions. https://omahaproxy.appspot.com/ and https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html can be used in combination. However, exact binary builds for a specific version may not exist from what I can tell. So the best shot would still be to build from source based on the tag.

**Comment by adolfintel** [comment]
It's the same thing as I said. The binaries for a specific build are not always available, so even if I could get the build number from there (doable but not immediate) it may not exist in the Chromium build repo.
Building from source is possible but I don't have the infrastructure to support that.

**Comment by pgera** [comment]
Yes, building chromium from source isn't trivial. It takes really long. I don't know if the free hosted ci services would be sufficient to build it at a regular frequency.

**Comment by Buxdehuda** [comment]
Retrieving "branch_base_position" from http://omahaproxy.appspot.com/all?channel=stable&os=android should give you the correct build number as far as I can tell.

**Comment by adolfintel** [comment]
@Buxdehuda Is this service reliable? Who's behind it? This would be perfect but I need a guarantee that it won't be taken down after in a few months ir if the author gets bored

**Comment by Buxdehuda** [comment]
I found a link to it on this site: https://www.chromium.org/developers/version-numbers so I guess it is at least somehow official. Falling back to the current method probably wouldn't hurt though

**Comment by adolfintel** [comment]
I guess it's worth a try, expect an update in a few days.

**Comment by adolfintel** [comment]
Oh this is awesome, I published the update 3 days ago and now http://omahaproxy.appspot.com/all?channel=stable&os=android is pointing at a build number that doesn't even exist.
I'm gonna get lynched

**Comment by pgera** [comment]
I thought this was a known limitation when we we were discussing this earlier. Specific builds aren't guaranteed to be available as binaries. Building from source is the only reliable option.

**Comment by adolfintel** [comment]
I'm implementing some fallback now, and I'm also putting dev as the default again just in case.
