### ISSUE TITLE
Dismiss Notification after installation

### ISSUE THREAD

**Issue by azumukupoe** [adolfintel/chromiumUpdater#18]
I sometimes dismiss notification on accident before installation. Could you make the notifications unswipeable?

**Comment by adolfintel** [comment]
Yes, I'll do it in the next few days

**Comment by azumukupoe** [comment]
@adolfintel Thanks for the quick response! I will look forward to it.

**Comment by adolfintel** [comment]
Done. It will take some time to propagate to f-droid and google play. You can get the APK directly from here: http://downloads.fdossena.com/geth.php?r=chromiumUpdater-apk
