### ISSUE TITLE
Some of the items in the settings gray out

### ISSUE THREAD

**Issue by azumukupoe** [adolfintel/chromiumUpdater#19]
The app is not hidden.
What should I do to fix this?
![Screenshot](https://i.imgur.com/SMesXU7.png)

**Comment by adolfintel** [comment]
I'm so sorry, I didn't get a notification about this issue.
I know it's been over a month...
The app icon should disappear within 30 seconds, or when the launcher is restarted. This was tested with the stock AOSP launcher, Trebuchet, Nova launcher, Pixel launcher, the MIUI launcher, Huawei's launcher, and the Touchwiz launcher.
Are you using some other unusual launcher?

**Comment by azumukupoe** [comment]
I'm using Nova Launcher.
I don't have the problem right now, so I will close this issue.
Thanks.

**Comment by adolfintel** [comment]
Ok. I see you've forked the project, are you making some changes?

**Comment by azumukupoe** [comment]
No, I'm just thinking of translating this to Japanese.
Is it okay?

**Comment by adolfintel** [comment]
Sure, send a PR if you want and I'll merge it
