### ISSUE TITLE
[FEATURE REQUEST] Add additional option(s)

### ISSUE THREAD

**Issue by pombadev** [adolfintel/chromiumUpdater#2]
Awesome app, would be nice to have these options:
- Manually check for update.
- Explicit option to set  `Update frequency` to manual.

**Comment by adolfintel** [comment]
Good idea, yeah, I'll do it in the next few days

**Comment by adolfintel** [comment]
Implemented in Version 1.6

**Comment by pombadev** [comment]
Thanks man!
