### ISSUE TITLE
New icon ?

### ISSUE THREAD

**Issue by jooola** [adolfintel/chromiumUpdater#22]
I would like to propose you some new icons for your app. Simply because the current icons in fdroid is really ugly IMO.
I saw you had to change the icons already because of the google policy right ?
Could you tell me more about this ?

I already [created some icons](https://github.com/jooola/chromiumUpdater/tree/master/contrib), just tell me if you like it , if we can use it ( google policy ? ) and if you want to tweak some details.
They all are SVG's so changing something would be really easy !
I used [the old chromium 11 SVG](https://commons.wikimedia.org/wiki/File:Chromium_11_Logo.svg) as base, and added on top of it the [sync icons from material icons](https://material.io/icons/#ic_sync).

I can also use a different icon like a down arrow or something, instead of the sync icon !

I'll push a PR once we find the right icon !

**Comment by adolfintel** [comment]
Hi joola, I appreciate your effort, but there is a reason why the current icon is ugly af: if you look back at the older versions of the app, you'll find the original icon, which is similar to yours; I was contacted by google because it was their trademark.
The current icon is a rough recreation that I did using just gimp, a couple of circles and 3 lines.

**Comment by jooola** [comment]
Ok, can't we still work on a new icon ?
We can keep the current design but enhance it ?
Do you have any ideas ?

**Comment by adolfintel** [comment]
Yes, you can work on a new icon of course; you can play around with the deisgn, as long as you're not using exactly the same shapes and/or colors of the original logo.
Feel free to experiment and send me the results

**Comment by jooola** [comment]
Ok I[ just made some others](https://github.com/jooola/chromiumUpdater/tree/master/contrib), am I still being to close to the original icon ? ( I mean we need to stick to it so we understand what the purpose of the app is ...)

**Comment by adolfintel** [comment]
It's hard do tell. v6 looks nice.
When they contacted me I sent them several icons and the only one that was different enough was the current one.

**Comment by jooola** [comment]
[Ok again new icon but based on v6](https://github.com/jooola/chromiumUpdater/blob/master/contrib/chromiumUpdater-v9.svg)

**Comment by adolfintel** [comment]
That looks nice.
I'll get in touch with you in 1-2 days with the updated code so you can send the pull request yourself

**Comment by adolfintel** [comment]
Send me an email at dosse91@paranoici.org so I can send you the new version
