### ISSUE TITLE
java.io.FileNotFoundException when trying to download an update

### ISSUE THREAD

**Issue by tdkl** [adolfintel/chromiumUpdater#24]
Hi, 

suddenly I get this error when trying to download a new update (stable branch): 

![screenshot_20180601-162749](https://user-images.githubusercontent.com/1429957/40857235-d31235f6-65da-11e8-83c0-a489f4c9242f.png)

App worked fine couple days ago, but now there's suddenly this issue. Reinstalling the app doesn't help.

**Comment by adolfintel** [comment]
It looks like https://commondatastorage.googleapis.com/chromium-browser-snapshots/Android/ isn't working properly, or maybe they deleted some builds.
I'll take down the app temporarily before I get lynched by bad reviews again.

**Comment by adolfintel** [comment]
Ok I looked into it a bit better, it's not google's fault, or the app's fault, it's this guy's fault
http://omahaproxy.appspot.com/all?channel=stable&os=android
His service is pointing to a "stable" build number that doesn't exist...

**Comment by adolfintel** [comment]
I'll see if I can find a solution, meanwhile, uninstall the app or use the latest builds instead of stable

**Comment by tdkl** [comment]
Oh, so it's only the stable branch, I'll switch back to dev then, thank you!

**Comment by adolfintel** [comment]
It's ridiculous, I added this feature 3 days ago and already they're chainging things

**Comment by tdkl** [comment]
Yeah, that's why I didn't even thought that only the stable branch URL was failing. Perhaps updating the app so that the dev build is back as default wouldn't be bad. Or perhaps asking people which branch to download from at first launch, because it starts downloading automatically.

**Comment by adolfintel** [comment]
Yeah, I'm definitely putting dev as the default again, and I'm also adding some fallback so that if the stable build number is wrong, it finds and downloads the nearest one. Absolute bullshit

**Comment by adolfintel** [comment]
Should be fixed now, wanna test it?
[app-release.zip](https://github.com/adolfintel/chromiumUpdater/files/2063879/app-release.zip)

**Comment by tdkl** [comment]
I've uninstalled the Google build and installed this one. Developer build was default again, but it actually downloaded the stable 67.x build :)

**Comment by adolfintel** [comment]
I'll upload the new version tomorrow morning then.

**Comment by tdkl** [comment]
Ok, thanks for the help
