### ISSUE TITLE
autoupdater 1.8 broken

### ISSUE THREAD

**Issue by zoof** [adolfintel/chromiumUpdater#25]
When I upgraded to 1.8, Auto Updater stopped working.  Every couple of seconds, the Auto Updater icon would flash in the task bar but nothing would happen.

Running LineageOS (14.1-20171204-NIGHTLY-d2vzw) on a Verizon Samung S3.

**Comment by adolfintel** [comment]
It was fixed in 1.8.1, update it and it will work again.
