### ISSUE TITLE
Could not parse package

### ISSUE THREAD

**Issue by killerbees19** [adolfintel/chromiumUpdater#26]
[I know, this is probably not related to this app.]

I've updated to v1.8.1 today. Now I can't install the latest or stable build. I'm using LineageOS 14.1, Android couldn't parse the downloaded package. Is there anything I could try or is Android 7.x no longer supported by Chromium Dev Builds?

(Sorry for my incomplete message before. I accidentally hit the submit button too early.)

http://666kb.com/i/dua365qursaqa84mx.png

**Comment by adolfintel** [comment]
I just tested it and it works fine on Lineage 14.1, I guess maybe the build failed for the specific version that you got and it generated an invalid APK.

**Comment by killerbees19** [comment]
Confirmed, works again. Sorry for the noise and thanks for your quick reply.
