### ISSUE TITLE
Installation of chromium fails on Android9. java.lang.NullPointerException: Attempt to invoke virtual method 

### ISSUE THREAD

**Issue by gstammw** [adolfintel/chromiumUpdater#29]
I'm running lineage os 16 (Android 9) with Magisk installed.
The autoupdater seems to complete the download of chromium, but fails to install it.
The installation method has already been set to "intent" (manual/no root), as I do not run root/supersu on this device.

`Exception:java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.addCategory(java.lang.String)' on a null object reference

Stack trace:
com.dosse.chromiumautoupdater.ChromiumUpdater$UpdateThread.downloadUpdate(ChromiumUpdater.java:350)
com.dosse.chromiumautoupdater.ChromiumUpdater$UpdateThread.run(ChromiumUpdater.java:92)

Device model: Moto Z
SDK Version: 28
App Version: 25
`

I enabled root in Magisk and changed the installation method to "pm" (root required), but the problem stays the same.

I believe this is related to a denied root-permission.  When I grant root in Magisk, the installation completes just fine.

Suggestion: when root is refused, the auto updater should stick to them "intent"-installation.
Obviously there is a bug that needs to be fixed to get this working.

**Comment by adolfintel** [comment]
It's not related to root or Magisk. It's only related to google breaking APIs for no reason.
I've fixed the root installation method last week, I'm now working on fixing the intent method (if that's even possible)

**Comment by adolfintel** [comment]
@gstammw it should be fixed now (at least, it works on my phone). I will release the APK in a few minutes

If you got the app from F-Droid, it might take a few days before you get an update.
If you got it from Google Play you will NOT get an update because the app was removed from there

**Comment by gstammw** [comment]
Thanks. I updated to 1.8.4 and removed root. Installation method "intent" (manual/no root) is working now.
