### ISSUE TITLE
Modify description text to reflect project reality

### ISSUE THREAD

**Issue by licaon-kter** [adolfintel/chromiumUpdater#3]
Meaning this line is not honest:
`It's basically Chrome without all the Google features (and spying).`

Some issues:
* how is Data saving implemented **without** Google servers exactly?
* why does it try to connect to a dozen *.google.com sites all the time?

**Comment by adolfintel** [comment]
Well those are official builds, I'm not building them.
You have a point though, Chromium has some of Chrome's features so I'll remove that.
