### ISSUE TITLE
Compare versions before download?

### ISSUE THREAD

**Issue by wchen342** [adolfintel/chromiumUpdater#32]
Currenly it seems the download will always happen regardless of installed version of chromium. Can a version comparison be added so only newer version will be downloaded?

**Comment by adolfintel** [comment]
It's already implemented: https://github.com/adolfintel/chromiumUpdater/blob/7ef9077c8d23307b43290652fac3933431bc1a62/ChromiumAutoUpdater/app/src/main/java/com/dosse/chromiumautoupdater/ChromiumUpdater.java#L193

Are you having problems with it?

**Comment by wchen342** [comment]
When I click update now it will always start the download. Is that intended?

Update: Ok I read the code, and see the `Update Now` button will always force a download. I will suggest adding a "newest version available" in the main window, so that users can know whether they need to update if using manual mode.

**Comment by adolfintel** [comment]
It's intended, that button forces the download, even if it's the same version

On June 9, 2019 9:10:33 PM GMT+02:00, wchen342 <notifications@github.com> wrote:
>When I click update now it will always start the download. Is that
>intended?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/adolfintel/chromiumUpdater/issues/32#issuecomment-500237321

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by alperovitz** [comment]
Two all orbot is at 16.1 Bata 1 just so you too all

**Comment by alperovitz** [comment]
Wops I was wrong it is 16.1.0 Bata 4
