### ISSUE TITLE
/app/system install option and/or aurora services install option plus hiding

### ISSUE THREAD

**Issue by SkyyySi** [adolfintel/chromiumUpdater#33]
Both systemizing and aurora services allow to install updates 100% in the background (so you don't even get a "permission granted" message from Magisk), would be nice if you could add them. An option to hide the app would also be nice (even if it would mean I have to reinstall to change settings).

**Comment by adolfintel** [comment]
I appreciate your input, but at this point this app has no reason to exist and will be removed from F-Droid and archived soon.
If you add the [Bromite repo](https://www.bromite.org/fdroid) to F-Droid you can get updates for Bromite (or Chromium) more easily.
