### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by PanderMusubi** [adolfintel/chromiumUpdater#5]
The build of Chromium installed by https://github.com/andDevW/getChromium seems to have better performance and is less clunky. What are (well-tested) experiences by others? If there is indeed a feasible improvement, should that imply another build of Chromium being made/offered via chromiumUpdater?

**Comment by adolfintel** [comment]
From GetChromium.java, lines 48-49:
private final String urlL = "https://commondatastorage.googleapis.com/" +
            "chromium-browser-snapshots/Android/LAST_CHANGE";

That's the same builds I'm installing.

**Comment by PanderMusubi** [comment]
Thanks for invetigating. Perhaps it was a subjective observation from me or a coincidence in the performance of the websites I was testing with.
