### ISSUE TITLE
Error: java.io.FileNotFoundException: ...

### ISSUE THREAD

**Issue by mahdiG** [adolfintel/chromiumUpdater#8]
Hi. I tried to download Chromium using your app on LineageOS 14.1 (nightly) on Redmi Note 3 (kenzo) and got the error. Can't expand the notification to see the full error.
![screenshot_20170205-185915](https://cloud.githubusercontent.com/assets/4989445/22627365/206ed450-ebd7-11e6-97d9-9d2012e30ee5.png)

**Comment by adolfintel** [comment]
It looks like it couldn't find the update zip on google.
Does it happen every time you try to update?

**Comment by mahdiG** [comment]
Yes. I've tried reinstalling the app several times but I get the same error every time.

**Comment by adolfintel** [comment]
Try this APK. It will generate a file named chrupd.log in your sdcard. Run the app and let it fail, then uninstall it and send me the log file so I can understand exactly what's going on.
(My fault for not letting that notification expand :( )

http://owncloud.fdossena.com/index.php/s/Mi8J9tgcXapTmel

**Comment by mahdiG** [comment]
[chrupd.txt](https://github.com/adolfintel/chromiumUpdater/files/753078/chrupd.txt)

**Comment by adolfintel** [comment]
Ok, it fails to fetch this file https://commondatastorage.googleapis.com/chromium-browser-snapshots/Android/LAST_CHANGE

But as you can see by clicking the link it exists so I guess the problem is somewhere else. Do you have privacy guard enabled? Any firewall?

**Comment by mahdiG** [comment]
No, I don't have them enabled. Clicking on that link opened a page with only the number 448184 on it.

**Comment by adolfintel** [comment]
Yes, that's the number of the last build of Chromium. I'll see if I can find any similar issue of FileNotFoundException connecting to https.

**Comment by adolfintel** [comment]
Try this: http://owncloud.fdossena.com/index.php/s/QhKjbvnMyNuQ5mn
It manually sets the HTTP header so maybe it will work? Logging is enabled so if send the log if it doesn't work.

**Comment by mahdiG** [comment]
Interestingly that page give me access denied when I try to reach it on my phone. it says the service is not available in my country :-/
But I wonder why it works fine on my computer where I don't use any vpn or anything like that.
Thanks anyway for your good support :)

**Comment by adolfintel** [comment]
Wow, I did not expect to see that. Do you live in China or something?

**Comment by mahdiG** [comment]
Iran :-/
Either Iran blocks some websites or some website blocks us.

**Comment by adolfintel** [comment]
Hmmm yeah I see some articles of some Google domains being blocked in Iran, so I guess googleapis.com is one of them.
